### ISSUE TITLE
Logo version didn't work

### ISSUE THREAD

**Issue by KFPlayer** [0x8008/mr9a#1]
I don't know why but it didn't work, the strange part is that I reboot de system and changed to default settings, then it stop booting, I'm using 2680v4 and quad channel 32gb ram.

I've used mi899 software to flash the bios as it says on the post.

Any thoughts on why it didn't work?

I'm not blaming you btw

EDIT: first start after I load the deafault changes in the BIOS the motherboard wasnt even beeping. And for some reason, now with only 16gb of ram it post, so maybe is something with quad channel? idk

**Comment by 0x8008** [comment]
`I'm not blaming you btw`

Relax :P 

What RAM are you using?

It might not work because of the Broadwell chip, keep in mind it's based off a dump off my own board post-flash, so it's not exactly agnostic. Hell, I didn't even expect it to get flashed by anyone, lol.

`EDIT: first start after I load the deafault changes in the BIOS the motherboard wasnt even beeping. And for some reason, now with only 16gb of ram it post, so maybe is something with quad channel? idk`

Unplug the PSU from the power, remove the BIOS battery for some time, press the power button/short the power jumper a few times, reinstall the battery and try again. You can also try the CMOS clear jumper as well before first boot after the BIOS battery removal

**Comment by KFPlayer** [comment]
I got it to work doing that but it wont start with quad channel (Im using 2xKllisre 2666mhz + 2x3200 Walram).
besides all that, I did it manually and now its working just fine, thanks btw <3

**Comment by 0x8008** [comment]
No issues.

The RAM being mixed + presumably non-ECC might be a bit of an issue, but that's just speculation.

**Comment by 0x8008** [comment]
No issues.

The RAM being mixed + presumably non-ECC might be a bit of an issue, but that's just speculation.
